import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Will pick up docs/intro.md and any other top-level docs
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        description: 'Learn ROS 2 fundamentals for humanoid robotics.',
        slug: '/module1-ros2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2', // Will pick up content from docs/module1-ros2
        },
      ],
    },
    // Future modules will go here
  ],
};

export default sidebars;