import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Will pick up docs/intro.md and any other top-level docs
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        description: 'Learn ROS 2 fundamentals for humanoid robotics.',
        slug: '/module1-ros2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2', // Will pick up content from docs/module1-ros2
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Module 2 Overview',
        description: 'Learners create and interact with digital twins in simulation environments.',
        slug: '/module2-digital-twin',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module2-digital-twin', // Will pick up content from docs/module2-digital-twin
        },
      ],
    },
    // Future modules will go here
  ],
};

export default sidebars;
