import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Will pick up docs/intro.md and any other top-level docs
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        description: 'Learn ROS 2 fundamentals for humanoid robotics.',
        slug: '/module1-ros2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2', // Will pick up content from docs/module1-ros2
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Module 2 Overview',
        description: 'Learners create and interact with digital twins in simulation environments.',
        slug: '/module2-digital-twin',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module2-digital-twin', // Will pick up content from docs/module2-digital-twin
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'generated-index',
        title: 'Module 3 Overview',
        description: 'Learners integrate advanced AI capabilities into their simulated humanoid using NVIDIA Isaac SDK.',
        slug: '/module3-ai-brain',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module3-ai-brain', // Will pick up content from docs/module3-ai-brain
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA Robotics)',
      link: {
        type: 'generated-index',
        title: 'Module 4 Overview',
        description: 'Learners connect vision, language, and action into a cohesive system for humanoid robotics.',
        slug: '/module4-vla',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module4-vla', // Will pick up content from docs/module4-vla
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {
        type: 'generated-index',
        title: 'Contributing Guide',
        slug: '/contributing',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing', // Will pick up content from docs/contributing
        },
      ],
    },
    // Future modules will go here
  ],
};

export default sidebars;
